### ISSUE TITLE
Using a custom volume with docker-compose

### ISSUE THREAD

**Issue by JamesDimonaco** [evoesports/docker-armagetronad#3]
when trying to save the data for the container in the same place as my docker-compose file 

`version: "3.8"
services:
  armagetron:
    image: evoesports/armagetronad:latest
    ports:
      - 4534:4534/udp
    volumes:
      - ./armagetron_data:/armagetronad
volumes:
  armagetron_data:`
  
  I get this error
  
  docker-compose up
Recreating 856be6bffa79_server_armagetron_1 ... done
Attaching to server_armagetron_1
armagetron_1  | touch: /armagetronad/var/input.txt: No such file or directory
server_armagetron_1 exited with code 1

it seems to work fine with a named volume

**Comment by ItsPhenom** [comment]
It seems like to be an issue with bind mounts in Docker [since 2014](https://github.com/moby/moby/issues/4361) or so.
Using a bind mount effectively renders all present files in the location inside of the container useless.
According to [this](https://github.com/moby/moby/issues/19990#issuecomment-248955005) comment, you can use the `docker volume` command to create a named volumed wherever you like and use it.

I quickly tested the workaround and it works.
Create the volume in your desired location, in my example inside a folder in my home dir:
`docker volume create --opt type=none --opt device=~/armagetrontest/armagetron_data --opt o=bind armagetronad_data`
And then just modify your docker-compose.yml to use that volume:
```
version: "3.8"
services:
  armagetron:
    image: evoesports/armagetronad:latest
    ports:
      - 4534:4534/udp
    volumes:
      - armagetron_data:/armagetronad
volumes:
  armagetron_data:
```

From what I could see the devs are also actually advising against using bind mounts, because they are old and have less functionality than volumes, and are generally meant to bind in files or directories from the host into the container. While a volume tells the container to put everything it has into the volume.

**Comment by JamesDimonaco** [comment]
the problem I was having was every time i ran docker-compose up -d I would see

```
Creating volume "server_armagetron_data" with default driver**
Creating server_armagetron_1 ... done
```

after checking the volumes i had after running your command i saw that it wasn't using my new volume 

```
docker volume ls
DRIVER    VOLUME NAME
local     armagetron_data
local     server_armagetron_data
```

after further investgation and a bit of gpt help i managed to get my compose file to use the defined volume like so 

```
version: "3.8"
services:
  armagetron:
    image: evoesports/armagetronad:latest
    ports:
      - 4534:4534/udp
    volumes:
      - armagetron_data:/armagetronad
volumes:
  armagetron_data:
    external: true

```

    
  Thank you @ItsPhenom for your suggestion 
    external: true is all i needed
